[repository]
name = "change wwallpapers"
authors = ["polyface"]
commit_pins = [
    [
        "3bb9c7c5cf4f2ee30bf821501499f2308d616f94",
        "efee74a7404495dbda70205824d6e9fc923ccdae",
    ],
    [
        "d74607e414dcd16911089a6d4b6aeb661c880923",
        "efee74a7404495dbda70205824d6e9fc923ccdae",
    ],
]
[plugin-name]
description = "plugin to change some of my wallpapers on boot"
authors = ["polyface"]
output = "wallpapers.so"
build = ["make all"]
